---

#- debug: msg="{{  hostvars[dockerswarm_manager_hostname]['dockerswarm_manager_token']['stdout'] }}"
- debug: msg="{{ hostvars[dockerswarm_manager_hostname]['swarm_facts']['swarm_facts']['JoinTokens']['Manager'] }}"
  when:
    - dockerswarm_manager
  tags:
    - never
    - debug

- debug: msg="{{ hostvars[dockerswarm_manager_hostname]['ansible_host'] }}:{{ dockerswarm_port }} "

- name: "join swarm as manager "
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_host }}"
    join_token: "{{ hostvars[dockerswarm_manager_hostname]['swarm_facts']['swarm_facts']['JoinTokens']['Manager'] }}"
    remote_addrs: "{{ hostvars[dockerswarm_manager_hostname]['ansible_host'] }}:{{ dockerswarm_port }}"
  become: YES
  when:
    - dockerswarm_manager
  tags:
    - add_manager
    - swarm_manager
