---

#- debug: msg="{{ hostvars[dockerswarm_manager_hostname]['dockerswarm_worker_token']['stdout'] }}"

- name: "join swarm as worker "
  shell: |
    docker swarm join \
    --token {{ hostvars[dockerswarm_manager_hostname]['dockerswarm_worker_token']['stdout'] }} \
    {{ hostvars[dockerswarm_manager_hostname]['ansible_host'] }}:{{ dockerswarm_port }}
  become: YES
  when:
    - "docker_info.stdout.find('Swarm: inactive') != -1"
    - dockerswarm_worker
  tags:
    - add_worker
    - swarm_worker