---
# init swarm manager master

- name: Init swarm manager master
  docker_swarm:
    advertise_addr: "{{ ansible_host }}"
    listen_addr: "{{ ansible_host }}"
    state: present
  register: swarm_facts
  become: YES
  when:
    - dockerswarm_managermaster
  tags:
    - init
    - swarm_manager_master

- debug: msg="{{ hostvars[dockerswarm_manager_hostname]['swarm_facts']['swarm_facts']['JoinTokens'] }}"
  tags:
    - never
    - debug
