---
# tasks file for ansible-dockerswarm

- include_tasks: prerequisites.yml
  tags:
    - always

# - name: "gather docker info "
#   shell: docker info
#   register: docker_info
#   become: YES
#   changed_when: False
#   tags:
#     - default
#     - always

- include_tasks: init_swarm_master.yml
  when: dockerswarm_managermaster
  tags:
    - init
    - swarm_manager_master

- include_tasks: add_manager.yml
  when:
#  - swarm_manager_master is undefined
#  - dockerswarm_manager
#  - not dockerswarm_worker
  tags:
    - add_manager

- include_tasks: add_worker.yml
  when:
  - swarm_manager_master is undefined
  - not dockerswarm_manager
  - dockerswarm_worker
  tags:
    - add_worker
